### PR TITLE
Adjustments to help bring package back to CRAN

### LINKED ISSUE #117: Fix brolgar package Alias
Dear maintainer,

You have file 'brolgar/man/brolgar.Rd' with \docType{package}, likely
intended as a package overview help file, but without the appropriate
PKGNAME-package \alias as per "Documenting packages" in R-exts.

This seems to be the consequence of the breaking change

>  Using @docType package no longer automatically adds a -package alias.
  Instead document _PACKAGE to get all the defaults for package
  documentation.

in roxygen2 7.0.0 (2019-11-12) having gone unnoticed, see
<https://github.com/r-lib/roxygen2/issues/1491>.

As explained in the issue, to get the desired PKGNAME-package \alias
back, you should either change to the new approach and document the new
special sentinel

```
  "_PACKAGE"
```

or manually add

```
  @aliases brolgar-package
```

if remaining with the old approach.

### PR DESCRIPTION
**Pull request by olivroy**
Fixes #117 

tidyselect deprecation warnings.
I accepted snapshots with ggplot2 3.5.0
Updated gh actions with `usethis::use_github_action()`.

There is one failure I can't seem to reproduce. You will see in the logs, but summary_slope seems to have lost one row, and I don't know if it is intentional o not.

I also removed unused packages from Suggests. (only leaving those used for examples, vignettes + tests) (readr is only used for creating a data in data-raw. markdown in not used, covr is used for the coverage (gh action installs it the same way the pkgdown gh action installs pkgdown)

Also removed what I assumed to be old vdiffr output.

Note that I see [this failure](https://github.com/njtierney/brolgar/actions/runs/7995186579/job/21836773726?pr=118#step:6:297) locally, but I don't know what is causing it, nor if it is intended.

I don't understand the r-devel one, nor do I see it on Windows 4.3.2

### CODE REVIEW

**Comment by njtierney** [comment]
Wow, thank you @olivroy !

**Comment by olivroy** [comment]
@njtierney this should fix a first round of issues. (the cached Matrix version = 1.6-2) was the culprit for vignette build failures!

**Comment by njtierney** [comment]
Thanks so much again! I'm just going to run some checks locally, but I should be able to push this along very soon!

**Comment by olivroy** [comment]
Hi Nick, just wanted to remind you of this!

I have not had the chance to upgrade to R 4.4 yet, but if you have, maybe the failure is easier to reproduce locally?

**Comment by njtierney** [comment]
Thanks @olivroy ! This works locally for me, I'm not trusting GH actions right now, I've heard that there are a bunch of issues at the moment with GH actions. 

Thanks again for all your help with this, and for the prompt! I had a small bug that I encountered, which should be solved now.

**Review by njtierney — APPROVED** [review]
Thanks again for your work on this @olivroy !

**Comment by njtierney** [comment]
Re 

> There is one failure I can't seem to reproduce. You will see in the logs, but summary_slope seems to have lost one row, and I don't know if it is intentional o not.

I believe this is just due to something random, this all looked fine to me otherwise.

**Pull request merged**
